import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        p{
          font-size: 20px;
          font-family: Arial, Helvetica, sans-serif;
        }
        h3{
          font-size: 25px;
          margin-bottom: -5px;
        }
      `}</style>
      <Head>
        <title>HuntingCoder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='keyword' content='nextjs, huntingcoder, blog'></meta>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Welcome to HuntingCoder
        </h1>
         <div className={styles.imgwrapper}>
        <img className={styles.homeimg} src="/images/codding.jpg" alt="indeximg" width={375} height={250} />
         </div>
        <p className={styles.description}>
          A blog for hunting coders by huntingcoder.
        </p>

       

        <div className={styles.blogs}>
             <h2 className={styles.popularblog}>Popular Blogs</h2>
             <div className={styles.blogItem}>
               <h3>How to learn javascript in 2022?</h3>
               <p>Javascript is a programming language which gives logic in code! Lorem ipsum dolor?</p>
               <button className={styles.btn}>Read More..</button>
             </div>
             <div className={styles.blogItem}>
               <h3>Popular programming language in 2022?</h3>
               <p>Javascript, Python, Java are popular programming languages in 2022! Lorem ipsum.</p>
               <button className={styles.btn}>Read More..</button>
             </div>
             <div className={styles.blogItem}>
               <h3>Popular framework of Javascript!</h3>
               <p>React is most popular framework of javascript Lorem ipsum dolor sit.</p>
               <button className={styles.btn}>Read More..</button>
             </div>
             <div className="blogItem">
               <h3>Nextjs is framework of Javascript?</h3>
               <p>Nextjs is framework of react and react is framework of js! Lorem ipsum dolor sit!</p>
               <button className={styles.btn}>Read More..</button>
             </div> 
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
